import React from "react";
import "../index.css";

const InfoSection = () => {
  return (
    <div className="infoSection">
      <section>
        <div className="firstRow">
          <p className="p1">
            A new wave of collectibles is about to hit the blockchain.
          </p>
          <p className="p2">
            Characterised by soft lighting, vintage colour schemes and quirky
            costumes, these generative 3D TinyFaces are the addition to your NFT
            collection you've been waiting for.
          </p>
        </div>
        <div className="secondRow">
          <div className="card">
            <section>
              <div className="imageContainer">
                <img src="./images/face1.png" alt="" />
              </div>
              <div className="titleContainer">
                <h1>Thousands of unique NFTs</h1>
                <img src="./images/Vector.png" alt="" />
              </div>
              <p className="description">
                Each character is entirely unique and is generated by combining
                attributes such as colour palettes, skin tones, facial traits,
                outfits and accessories. With nearly endless combinations, all
                characters are guaranteed to be one of a kind.
              </p>
            </section>
          </div>
          <div className="card">
            <section>
              <div className="imageContainer">
                <img src="./images/face2.png" alt="" />
              </div>
              <div className="titleContainer">
                <h1>Secure the most rare</h1>
                <img src="./images/Vector.png" alt="" />
              </div>
              <p className="description">
                Even though no two Tinyfaces will ever be the same, some
                variations are rarer than others. Watch out for special
                accessories and raw materials - the rarer the attributes, the
                rarer your character will be.
              </p>
            </section>
          </div>
        </div>
        <div className="thirdRow">
          <section>
            <div className="left">
              <h1>Our environmental impact matters to us.</h1>
              <p>
                In order to enable our community to spend as little as possible
                in gas fees when minting, we opted for a contract made by Azuki
                called ERC721A, which allows minting multiple NFTs for
                essentially the same cost as minting a single one.
              </p>
            </div>
            <div className="right">
              <img src="./images/env1.png" alt="" />
            </div>
          </section>
        </div>
      </section>
    </div>
  );
};

export default InfoSection;
